// Comprehensive Fallout Shelter Data

const WEAPONS = {
    "None": "No Weapon",
    "032Pistol": ".32 Pistol",
    "032Pistol_Enhanced": "Enhanced .32 Pistol",
    "032Pistol_Rusty": "Rusty .32 Pistol",
    "10mmPistol": "10mm Pistol",
    "10mmPistol_Enhanced": "Enhanced 10mm Pistol",
    "10mmPistol_Hardened": "Hardened 10mm Pistol",
    "10mmPistol_Rusty": "Rusty 10mm Pistol",
    "AlienBlaster": "Alien Blaster",
    "AlienBlaster_Destabilizer": "Destabilizer",
    "AlienBlaster_Focused": "Focused Alien Blaster",
    "AlienBlaster_Tuned": "Tuned Alien Blaster",
    "AssaultRifle": "Assault Rifle",
    "AssaultRifle_Enhanced": "Enhanced Assault Rifle",
    "AssaultRifle_Hardened": "Hardened Assault Rifle",
    "AssaultRifle_Rusty": "Rusty Assault Rifle",
    "BBGun": "BB Gun",
    "BBGun_Enhanced": "Enhanced BB Gun",
    "BBGun_Hardened": "Hardened BB Gun",
    "BBGun_Rusty": "Rusty BB Gun",
    "Melee_BaseballBat": "Baseball Bat",
    "PipeRifle_Bayoneted": "Bayoneted Pipe Rifle",
    "Melee_ButcherKnife": "Butcher Knife",
    "CombatRifle": "Combat Rifle",
    "CombatShotgun": "Combat Shotgun",
    "CombatShotgun_DoubleBarrelled": "Double-Barrel Combat Shotgun",
    "CombatShotgun_Enhanced": "Enhanced Combat Shotgun",
    "CombatShotgun_Hardened": "Hardened Combat Shotgun",
    "GatlingLaser": "Gatling Laser",
    "GatlingLaser_Focused": "Focused Gatling Laser",
    "GatlingLaser_Overcharged": "Overcharged Gatling Laser",
    "GaussRifle": "Gauss Rifle",
    "GaussRifle_Enhanced": "Enhanced Gauss Rifle",
    "HuntingRifle": "Hunting Rifle",
    "HuntingRifle_Enhanced": "Enhanced Hunting Rifle",
    "HuntingRifle_Hardened": "Hardened Hunting Rifle",
    "HuntingRifle_Rusty": "Rusty Hunting Rifle",
    "Fatman": "Fat Man",
    "Flamer": "Flamer",
    "Flamer_Burnmaster": "Burnmaster",
    "Flamer_Napalmer": "Napalmer",
    "InstituteRifle": "Institute Rifle",
    "InstituteRifle_Excited": "Excited Institute Rifle",
    "JunkJet": "Junk Jet",
    "JunkJet_Flaming": "Flaming Junk Jet",
    "LaserPistol": "Laser Pistol",
    "LaserPistol_Focused": "Focused Laser Pistol",
    "LaserPistol_Rusty": "Rusty Laser Pistol",
    "LaserPistol_Tuned": "Tuned Laser Pistol",
    "LaserRifle": "Laser Rifle",
    "LaserRifle_Amplified": "Amplified Laser Rifle",
    "LaserRifle_Focused": "Focused Laser Rifle",
    "Magnum": "Magnum",
    "Magnum_ArmorPiercing": "Armor Piercing Magnum",
    "Magnum_Blackhawk": "Blackhawk",
    "Magnum_Enhanced": "Enhanced Magnum",
    "MissileGrenadeLauncher": "Missile Launcher",
    "MissileGrenadeLauncher_Guided": "Guided Missile Launcher",
    "Minigun": "Minigun",
    "Minigun_OlPainless": "Ol' Painless",
    "Minigun_Shredder": "Shredder",
    "PlasmaPistol": "Plasma Pistol",
    "PlasmaPistol_Focused": "Focused Plasma Pistol",
    "PlasmaThrower": "Plasma Thrower",
    "PlasmaThrower_Boosted": "Boosted Plasma Thrower",
    "PlasmaRifle": "Plasma Rifle",
    "PlasmaRifle_Focused": "Focused Plasma Rifle",
    "PipeRifle": "Pipe Rifle",
    "PipeRifle_Calibrated": "Calibrated Pipe Rifle",
    "RailwayRifle": "Railway Rifle",
    "SawedOffShotgun": "Sawed-Off Shotgun",
    "SawedOffShotgun_DoubleBarrelled": "Double-Barrel Sawed-Off Shotgun",
    "Shotgun": "Shotgun",
    "Shotgun_DoubleBarrelled": "Double-Barrel Shotgun",
    "Shotgun_Enhanced": "Enhanced Shotgun",
    "SniperRifle": "Sniper Rifle",
    "SniperRifle_Enhanced": "Enhanced Sniper Rifle",
    "Fist": "Fist",
    "Melee_FireHydrantBat": "Fire Hydrant Bat",
    "Melee_KitchenKnife": "Kitchen Knife",
    "Melee_PickAxe": "Pick Axe",
    "Melee_PoolCue": "Pool Cue",
    "Melee_Ripper": "Ripper",
    "Melee_Switchblade": "Switchblade",
};

const OUTFITS = {
    "None": "None",
    "AllNightware": "Nightwear",
    "AllNightware_Naughty": "Naughty Nightwear",
    "AmataSpecial": "Amata's Jumpsuit",
    "ArgyleSweater": "Accountant Outfit",
    "BaseballUniform": "Baseball Uniform",
    "BattleArmor": "Battle Armor",
    "BattleArmor_Heavy": "Heavy Battle Armor",
    "BattleArmor_Sturdy": "Sturdy Battle Armor",
    "BishopSpecial": "Clergy Outfit",
    "BittercupSpecial": "Bittercup's Outfit",
    "BOSUniform": "BoS Uniform",
    "BOSUniform_Advanced": "Advanced BoS Uniform",
    "BOSUniform_Expert": "Expert BoS Uniform",
    "BowlingShirt": "Drag Racer",
    "BusinessDress": "Agent Provocateur",
    "BusinessSuit": "Business Suit",
    "ButchSpecial": "Tunnel Snakes Outfit",
    "CasualFit": "Casual Fit",
    "CheckeredShirt": "Spring Casualwear",
    "ColonelSpecial": "Autumn's Uniform",
    "CombatArmor": "Combat Armor",
    "CombatArmor_Heavy": "Heavy Combat Armor",
    "CombatArmor_Sturdy": "Sturdy Combat Armor",
    "ComedianSpecial": "Comedian Outfit",
    "CromwellSpecial": "Confessor Cromwell's Rags",
    "Detective": "Detective Outfit",
    "DooWopOutfit": "Doo-Wop Singer",
    "DrLiSpecial": "Doctor Li's Outfit",
    "ElderLyonsSpecial": "Elder Lyon's Robe",
    "EmpressSpecial": "Republic Robes",
    "EngineerSpecial": "Engineer Outfit",
    "EulogyJonesSpecial": "Eulogy Jones' Suit",
    "FarHarborSpecial": "Tattered Longcoat",
    "FlightSuit": "Flight Suit",
    "FlightSuit_Advanced": "Advanced Flight Suit",
    "FlightSuit_Expert": "Expert Flight Suit",
    "FormalWear": "Formal Wear",
    "FormalWear_Fancy": "Fancy Formal Wear",
    "FormalWear_Lucky": "Lucky Formal Wear",
    "GreaserSpecial": "Greaser Outfit",
    "HandymanJumpsuit": "Handyman Jumpsuit",
    "HandymanJumpsuit_Advanced": "Advanced Jumpsuit",
    "HandymanJumpsuit_Expert": "Expert Jumpsuit",
    "HarknessSpecial": "Harkness' Security Uniform",
    "HazmatSuit": "Wasteland Gear",
    "HazmatSuit_Heavy": "Heavy Wasteland Gear",
    "HazmatSuit_Sturdy": "Sturdy Wasteland Gear",
    "Horseman_DeathJacket": "Death's Jacket",
    "Horseman_FamineVestment": "Famine's Vestment",
    "Horseman_PestilencePlating": "Pestilence's Plating",
    "Horseman_WarArmor": "War's Armor",
    "HunterGear_Bounty": "Bounty Hunter Gear",
    "HunterGear_Mutant": "Mutant Hunter Gear",
    "HunterGear_Treasure": "Treasure Hunter Gear",
    "InstituteJumper_Advanced": "Advanced Institute Jumper",
    "InstituteJumper_Expert": "Expert Institute Jumper",
    "JacketTshirt": "Motorcycle Jacket",
    "JamesSpecial": "Dad's Lab Uniform",
    "JerichoSpecial": "Jericho's Leather Armor",
    "JobinsonsJersey": "Rackie Jobinson's Jersey",
    "jumpsuit": "Vault Suit",
    "KingSpecial": "Medieval Ruler Outfit",
    "KnightSpecial": "Knight Armor",
    "LabCoat": "Lab Coat",
    "LabCoat_Advanced": "Advanced Lab Coat",
    "LabCoat_Expert": "Expert Lab Coat",
    "LeatherArmor": "Leather Armor",
    "LeatherArmor_Heavy": "Heavy Leather Armor",
    "LeatherArmor_Sturdy": "Sturdy Leather Armor",
    "LibrarianSpecial": "Librarian Outfit",
    "LifeguardOutfit": "Lifeguard Outfit",
    "LoungeShirt": "Bowling Shirt",
    "LucasSpecial": "Sheriff's Duster",
    "MayorSpecial": "Mayor Outfit",
    "MechanicJumpsuit": "Mechanic Jumpsuit",
    "MetalArmor": "Metal Armor",
    "MetalArmor_Heavy": "Heavy Metal Armor",
    "MetalArmor_Sturdy": "Sturdy Metal Armor",
    "MilitaryJumpsuit": "Military Fatigues",
    "MilitaryJumpsuit_Commander": "Commander Fatigues",
    "MilitaryJumpsuit_Officer": "Officer Fatigues",
    "MoiraSpecial": "Moira's RobCo Jumpsuit",
    "MoviefanSpecial": "Movie Fan Outfit",
    "MrBurkeSpecial": "Mr. Burke's Outfit",
    "NinjaSuit": "Ninja Outfit",
    "PolkaDotDress": "Polka Dot Sundress",
    "PowerArmor": "Power Armor",
    "PowerArmor_MkI": "Power Armor Mk I",
    "PowerArmor_T45a": "T-45a Power Armor",
    "PowerArmor_T45d": "T-45d Power Armor",
    "PowerArmor_T45f": "T-45f Power Armor",
    "PowerArmor_T51a": "T-51a Power Armor",
    "PowerArmor_T51d": "T-51d Power Armor",
    "PowerArmor_T51f": "T-51f Power Armor",
    "PowerArmor_T60a": "T-60a Power Armor",
    "PowerArmor_T60d": "T-60d Power Armor",
    "PowerArmor_T60f": "T-60f Power Armor",
    "PowerArmor_X01": "X-01 Power Armor",
    "PiperSpecial": "Piper's Outfit",
    "PrestonSpecial": "Preston's Outfit",
    "RadiationSuit": "Radiation Suit",
    "RadiationSuit_Advanced": "Advanced Radiation Suit",
    "RadiationSuit_Expert": "Expert Radiation Suit",
    "RaiderArmor": "Raider Armor",
    "RaiderArmor_Heavy": "Heavy Raider Armor",
    "RaiderArmor_Sturdy": "Sturdy Raider Armor",
    "RiotGear": "Merc Gear",
    "RiotGear_Heavy": "Heavy Merc Gear",
    "RiotGear_Sturdy": "Sturdy Merc Gear",
    "RothchildSpecial": "Scribe Rothchild's Robe",
    "SantaSuit_Original": "Original Santa Suit",
    "SarahSpecial": "Lyon's Pride Armor",
    "ScientistScrubs": "Junior Officer Uniform",
    "ScientistScrubs_Commander": "Commander Uniform",
    "ScientistScrubs_Officer": "Officer Uniform",
    "ScifiSpecial": "Sci-Fi Fan Outfit",
    "ScribeRobe": "Scribe Robe",
    "ScribeRobe_Elder": "Elder Robe",
    "ScribeRobe_Initiate": "Initiate Robe",
    "SequinDress": "Vault Socialite",
    "SlasherSpecial": "Horror Fan Outfit",
    "SodaFountainDress": "Soda Fountain Dress",
    "SoldierSpecial": "Soldier Uniform",
    "SpecialThemeHalloween": "Ghost Costume",
    "SpecialThemeHalloween2": "Skeleton Costume",
    "SpecialThemeThanksGiving": "Pilgrim Outfit",
    "SpecialThemeXmas": "Santa Suit",
    "SpecialThemeXmas2": "Elf Outfit",
    "SportsfanSpecial": "Sports Fan Outfit",
    "StarPaladinSpecial": "Cross' Power Armor",
    "SurgeonSpecial": "Surgeon Outfit",
    "SurvivorSpecial": "Survivor Armor",
    "Suspenders": "Bespoke Attire",
    "SweaterVest": "Pre-War Suburbanite",
    "Swimsuit": "Swimsuit",
    "SwingDress": "Swing Dress",
    "SynthArmor_Heavy": "Heavy Synth Armor",
    "ThreedogSpecial": "Three Dog's Outfit",
    "TiedBlouse": "Country Girl",
    "UtilityJumpsuit": "Armored Vault Suit",
    "WandererArmor": "Wanderer Armor",
    "WandererArmor_Heavy": "Heavy Wanderer Armor",
    "WandererArmor_Sturdy": "Sturdy Wanderer Armor",
    "WastelandSurgeon": "Wasteland Surgeon",
    "WastelandSurgeon_Doctor": "Wasteland Doctor",
    "WastelandSurgeon_Settler": "Wasteland Settler",
    "WrestlerSpecial": "Wrestler Outfit",
};

const ROOMS = [
    "Vault Door", "Overseer's Office", "Radio Station",
    "Medbay", "Science Lab", "Weapon Factory",
    "Outfit Factory", "Food Production", "Water Production",
    "Power Plant", "Storage", "Gym", "Dojo", "Bar",
    "Game Room", "Classroom", "Barber Shop", "Armory"
];

const SPECIAL_STATS = [
    { key: 's', name: 'Strength', short: 'S.' },
    { key: 'p', name: 'Perception', short: 'P.' },
    { key: 'e', name: 'Endurance', short: 'E.' },
    { key: 'c', name: 'Charisma', short: 'C.' },
    { key: 'i', name: 'Intelligence', short: 'I.' },
    { key: 'a', name: 'Agility', short: 'A.' },
    { key: 'l', name: 'Luck', short: 'L.' },
];
